language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer global require satooshi/php-coveralls
  - composer update --quiet

script:
  - phpunit -c phpunit.xml.dist

after_script:
  - coveralls
